apiVersion: v2
name: sts
description: A Helm chart for deploying stateful applications as StatefulSets
type: application
version: 2.0.1
appVersion: "latest"
home: https://pfnapp.github.io/charts
maintainers:
  - name: pfnapp-team
keywords:
  - statefulset
  - ingress
  - haproxy
  - configmap
  - secret
  - persistent-volume
dependencies:
- name: common
  version: "1.0.1"
  repository: "file://../common"