# Default values for nginx chart
# This inherits from the deploy chart and configures it for Nginx

deploy:
  # Application configuration
  app:
    # This sets app.kubernetes.io/name label for proper log aggregation
    name: "nginx"
    version: "1.24"

  # Use deployment (not statefulset) for nginx
  deploymentType: "deployment"

  # Replica count
  replicaCount: 2

  # Nginx image configuration
  image:
    repository: "nginx"
    tag: "1.24-alpine"
    pullPolicy: IfNotPresent

  # Service configuration
  service:
    enabled: true
    type: ClusterIP
    port: 80
    targetPort: 80
    annotations: {}

  # Ingress configuration with HAProxy
  ingress:
    enabled: true
    className: "haproxy"
    annotations:
      haproxy.org/load-balance: "roundrobin"
      haproxy.org/check: "true"
    hosts:
      - host: nginx.local
        paths:
          - path: /
            pathType: Prefix
    tls: []

  # Container ports
  containerPorts:
    - containerPort: 80
      name: http

  # Health checks
  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5

  # Resource limits
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

  # Autoscaling
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70

  # ConfigMap for custom nginx configuration
  configMap:
    enabled: true
    data:
      NGINX_HOST: "nginx.local"
      NGINX_PORT: "80"

  # Node selector for nginx pods
  nodeSelector: {}

  # Tolerations (empty by default)
  tolerations: []

  # Logging configuration
  logging:
    enabled: true