{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sts.fullname" . }}-config
  labels:
    {{- include "sts.labels" . | nindent 4 }}
data:
  config: "{{ include "sts.fullname" . }}-config"
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- include "sts.volumeMounts.resources" . }}