apiVersion: v2
name: nginx
description: A simple Nginx deployment chart using the dynamic deploy chart
type: application
version: 0.1.7
appVersion: "1.24"
home: https://github.com/pfnapp/charts
maintainers:
  - name: pfnapp-team
keywords:
  - nginx
  - web
  - server
dependencies:
  - name: deploy
    version: "0.1.7"
    repository: "file://../deploy"
