{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy.fullname" . }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "deploy.selectorLabels" . | nindent 4 }}
{{- end }}

{{- if and (eq .Values.deploymentType "statefulset") .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.statefulset.serviceName | default (printf "%s-headless" (include "deploy.fullname" .)) }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "deploy.selectorLabels" . | nindent 4 }}
{{- end }}