name: Release Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.1

      - name: Add Helm repositories
        run: |
          # Add any external chart repositories your charts depend on
          # Example: helm repo add bitnami https://charts.bitnami.com/bitnami
          
          # Only update if repositories exist
          if helm repo list >/dev/null 2>&1; then
            helm repo update
          else
            echo "No repositories configured, skipping update"
          fi

      - name: Update chart dependencies
        run: |
          for chart in pfnapp/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Updating dependencies for $chart"
              helm dependency update "$chart"
            fi
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: pfnapp
        env:
          CR_TOKEN: "${{ secrets.GH_TOKEN }}"
