name: Release Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.1

      - name: Add Helm repositories
        run: |
          # Add any external chart repositories your charts depend on
          # Example: helm repo add bitnami https://charts.bitnami.com/bitnami
          
          # Only update if repositories exist
          if helm repo list >/dev/null 2>&1; then
            helm repo update
          else
            echo "No repositories configured, skipping update"
          fi

      - name: Lint charts
        run: |
          for chart in pfnapp/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Linting $chart"
              helm lint "$chart"
            fi
          done

      - name: Template charts
        run: |
          for chart in pfnapp/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Templating $chart"
              helm template test "$chart"
              # Test with StatefulSet configuration
              helm template test "$chart" --set deploymentType=statefulset
            fi
          done

      - name: Run Helm tests
        run: |
          for chart in pfnapp/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Running tests for $chart"
              # Test deployment configuration
              if helm install test-deployment "$chart" --dry-run --debug; then
                echo "Deployment test passed for $chart"
              else
                echo "Deployment test failed for $chart"
                exit 1
              fi
              
              # Test StatefulSet configuration
              if helm install test-statefulset "$chart" --set deploymentType=statefulset --dry-run --debug; then
                echo "StatefulSet test passed for $chart"
              else
                echo "StatefulSet test failed for $chart"
                exit 1
              fi
            fi
          done

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.1

      - name: Add Helm repositories
        run: |
          # Add any external chart repositories your charts depend on
          # Example: helm repo add bitnami https://charts.bitnami.com/bitnami
          
          # Only update if repositories exist
          if helm repo list >/dev/null 2>&1; then
            helm repo update
          else
            echo "No repositories configured, skipping update"
          fi

      - name: Update chart dependencies
        run: |
          for chart in pfnapp/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Updating dependencies for $chart"
              helm dependency update "$chart"
            fi
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: pfnapp
        env:
          CR_TOKEN: "${{ secrets.GH_TOKEN }}"
